const GET_TODO_ITEM_REQUEST = 'GET_TODO_ITEM_REQUEST'
const GET_TODO_ITEM_RECEIVE = 'GET_TODO_ITEM_RECEIVE'
const GET_TODO_ITEM_FAILURE = 'GET_TODO_ITEM_FAILURE'

const DELETE_TODO_ITEM_REQUEST = 'DELETE_TODO_ITEM_REQUEST'
const DELETE_TODO_ITEM_RECEIVE = 'DELETE_TODO_ITEM_RECEIVE'
const DELETE_TODO_ITEM_FAILURE = 'DELETE_TODO_ITEM_FAILURE'

const EDIT_TODO_ITEM_REQUEST = 'EDIT_TODO_ITEM_REQUEST'
const EDIT_TODO_ITEM_RECEIVE = 'EDIT_TODO_ITEM_RECEIVE'
const EDIT_TODO_ITEM_FAILURE = 'EDIT_TODO_ITEM_FAILURE'

export default {
    GET_TODO_ITEM_REQUEST,
    GET_TODO_ITEM_RECEIVE,
    GET_TODO_ITEM_FAILURE,

    DELETE_TODO_ITEM_REQUEST,
    DELETE_TODO_ITEM_RECEIVE,
    DELETE_TODO_ITEM_FAILURE,

    EDIT_TODO_ITEM_REQUEST,
    EDIT_TODO_ITEM_RECEIVE,
    EDIT_TODO_ITEM_FAILURE
}